### ISSUE TITLE
Backport limiting output API with 'skip' and 'limit' from scoutfish

### ISSUE THREAD

**Issue by gbtami** [mcostalba/chess_db#24]

**Comment by sshivaji** [comment]
Finally, chessui is integrated with chess_db. Live version at drshivaji.com:8888 (maybe we can reserve scoutfish.org, or chessui.org)?

Currently paging is not yet supported for game offsets (though the load book moves, load game headers, and get game content all work). Would be cool to enable paging when 'skip' and 'limit' are supported for chess_db :)

**Comment by sshivaji** [comment]
I have sent a pull request that does this. From a UI perspective, this is needed when reading a big database.

**Comment by mcostalba** [comment]
merged
