### ISSUE TITLE
"No valid games found!" not handled in chess_db.py

### ISSUE THREAD

**Issue by gbtami** [mcostalba/chess_db#29]
If a .pgn has only variant games self.p.expect(BOOK_MAKE_DONE_REGEX) is waiting forever now.

**Comment by sshivaji** [comment]
What should the regex be then? Do you have a variant games file and the output of the command?

We can support more than one regex with self.p.expect([BOOK_MAKE_REGEX, VARIANT_MAKE_REGEX])

**Comment by gbtami** [comment]
Yes it's in #32

**Comment by mcostalba** [comment]
Already fixed upstream at lower level.
