### ISSUE TITLE
regex for find command (in chess_db.py) is not accurate

### ISSUE THREAD

**Issue by sshivaji** [mcostalba/chess_db#37]
I put in the code to look for a line ending brace }. However, that is wrong when running many large tests. It turns out that this can be at the middle of the output.

We cannot test for EOF output either as the UCI executable is still running.

My solution for which I will issue a corresponding PR is to add a CTRL-A character at the end of the output of the find command. This still allows one to see the output fine if running on pure command line, but in python mode, we will know when the terminator is.

**Comment by mcostalba** [comment]
Can you please post a specific test case?

**Comment by sshivaji** [comment]
I tried but it's not easy, it's a bit non deterministic. Sometimes an exception happens, sometimes it does not. It's more easy to see when u are pagination on the UI page by page (you can see it randomly after 3 to 7 queries). I like the readyok solution. My solution was done quickly to enable the UI

**Comment by sshivaji** [comment]
I did not realize the UCI change to accept the "isready" command was straightforward like you demonstrated (I was thinking of multi-threaded isready, which is of course not needed). It would have been far easier for me to submit that as a pull request than do the ctrl-a or other character hacks. Apologies and thanks for the fix!

**Comment by mcostalba** [comment]
In scoutFish due to multithreading It is indeed more complex, but here it
ended up to be far easier than expected.
